#!/bin/sh

# Used chatgpt for help on this startup script. Chat link: https://chatgpt.com/share/6991636f-aaa8-8004-a62b-4535a61d3c93 

### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: AESD socket server
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
DAEMON_ARGS="-d"
NAME=aesdsocket
PIDFILE=/var/run/${NAME}.pid

start() {
    echo "Starting ${NAME}..."
    start-stop-daemon -S -n ${NAME} -a ${DAEMON} -- ${DAEMON_ARGS}
}

stop() {
    echo "Stopping ${NAME}..."
    start-stop-daemon -K -n ${NAME}
}

case "$1" in
  start) start ;;
  stop) stop ;;
  restart) stop; start ;;
  *) echo "Usage: $0 {start|stop|restart}"; exit 1 ;;
esac

exit 0

